baseURL = "https://www.vmateevitsi.com/"
canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "en-US"
paginate = 7
rssLimit = 10
theme = ["hugo-cloak-email"]
timeout = 60000

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"
    tabWidth = 4

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js"
    target = "assets/js/vendor/bootstrap"
  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/js/vendor/jquery"
  [[module.mounts]]
    source = "node_modules/rrssb/js"
    target = "assets/js/vendor/rrssb"
  [[module.mounts]]
    source = "node_modules/font-awesome/fonts"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/js/vendor/prism"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "static/typo"
  [[module.mounts]]
    source = "node_modules/photoswipe/dist"
    target = "assets/js/vendor/photoswipe"
  [[module.mounts]]
    source = "node_modules/photoswipe/dist/default-skin"
    target = "static/images/vendor/photoswipe"
  [[module.mounts]]
    source = "node_modules/processing-js"
    target = "assets/js/vendor/processing"
  [[module.mounts]]
    source = "node_modules/ga-lite/dist"
    target = "static/js/vendor/ga-lite"
  [[module.mounts]]
    source = "node_modules/lazysizes"
    target = "assets/js/vendor/lazysizes"
  [[module.mounts]]
    source = "node_modules/academicons/fonts"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/slick-carousel/slick"
    target = "assets/js/vendor/slick"
  [[module.mounts]]
    source = "node_modules/slick-carousel/slick"
    target = "static/js/vendor/slick"
  [[module.mounts]]
    source = "node_modules/jquery-countdown/dist"
    target = "assets/js/vendor/jquery-countdown"
  [[module.mounts]]
    source = "node_modules/moment"
    target = "assets/js/vendor/moment"
  [[module.mounts]]
    source = "node_modules/moment-timezone/builds"
    target = "assets/js/vendor/moment-timezone"
  [[module.mounts]]
    source = "node_modules/popper.js/dist"
    target = "assets/js/vendor/popper"
  [[module.mounts]]
    source = "node_modules/requirejs"
    target = "assets/js/vendor/requirejs"
  [[module.mounts]]
    source = "node_modules/animejs/lib"
    target = "assets/js/vendor/animejs"

[taxonomies]
  category = "categories"

[permalinks]
  blog = "/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 100
    [[related.indices]]
    name = "date"
    weight = 10

[security]
  [security.exec]
    allow = ['^npx$', '^babel$']
