[[main]]
  identifier = "home"
  name = "home"
  url = "/"
  weight = 1

[[main]]
  identifier= "news"
  name = "news"
  url = "/news/"
  weight = 2

[[main]]
  identifier = "press"
  name = "press"
  url = "/press/"
  weight = 3

[[main]]
  identifier = "videos"
  name = "videos"
  url = "/videos/"
  weight = 4

[[main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 5

[[main]]
  identifier = "contact"
  name = "contact"
  url = "/contact/"
  weight = 6

