title = "Victor Mateevitsi, PhD"
titleSeparator = "-"
titleAddition = "Researcher, Scientist, Engineer"
description = "I am a Human-Computer Interaction Research Scientist at GN Advanced Science, founder and chair of ChicagoCHI and co-founder of PICKLE. I also consult startups and companies on HCI, UX, Virtual Reality, Augmented Reality and emerging technologies"
images = ["VictorMateevitsi.jpg"]
twitterSite = "@mvictoras"
twitterCreator = "@mvictoras"
ogLocale = "en_US"
schemaType = "Person"
schemaLogo = "logo-vm.png"
schemaTwitter = "https://twitter.com/mvictoras"
schemaLinkedIn = "https://www.linkedin.com/in/mvictoras"
schemaSection = "news"
#siteLinksSearchBox = false

themeColor = "#fff"

googleAnalytics = "UA-6150752-1"

quality = 85
#bgColor = "#fff"
#landscapePhotoWidths = [900, 700, 500]
#portraitPhotoWidths = [1500, 1000, 750]
#lqipWidth = "20x"
articlePhotoSize = "688x381"
