title = "Victor Mateevitsi, PhD"
titleSeparator = "-"
titleAddition = "Researcher, Scientist, Engineer"
description = "Personal webpage."
#images = ["image-hyas.png"]
twitterSite = "@mvictoras"
twitterCreator = "@mvictoras"
ogLocale = "en_US"
schemaType = "Person"
#schemaLogo = "logo-hyas.png"
schemaTwitter = "https://twitter.com/mvictoras"
schemaLinkedIn = "https://www.linkedin.com/in/mvictoras"
#schemaSection = "news"
#siteLinksSearchBox = false

#themeColor = "#fff"

# googleAnalytics = "UA-99999999-1"

#quality = 85
#bgColor = "#fff"
#landscapePhotoWidths = [900, 700, 500]
#portraitPhotoWidths = [1500, 1000, 750]
#lqipWidth = "20x"
