baseURL = "/"
languageCode = "en-us"
title = "Victor Mateevitsi, PhD"
theme = "default"
relativeURLs = true
enableRobotsTXT = true

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/home/"
    weight = 1

  [[menu.main]]
    identifier= "news"
    name = "news"
    url = "/news/"
    weight = 2

  [[menu.main]]
    identifier = "press"
    name = "press"
    url = "/press/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact/"
    weight = 5

[[params.social]]
  name = "facebook"
  handle = "vmateevitsi"
  url = "https://www.facebook.com/"

[[params.social]]
  name = "twitter"
  handle = "mvictoras"
  url = "https://twitter.com/"
 
[[params.social]]
  name = "instagram"
  handle = "mvictoras"
  url = "https://www.instagram.com/"

[[params.social]]
  name = "linkedin"
  handle = "mvictoras"
  url = "https://www.linkedin.com/in/"

[options]
  image = "img/VictorMateevitsi.jpg"
