baseURL = "/"
languageCode = "en-us"
title = "Victor Mateevitsi"
theme = "default"
relativeURLs = true
enableRobotsTXT = true

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"

    [[menu.main]]
      identifier = "press"
      name = "Press"
      url = "/press/"
