baseURL = "/"
languageCode = "en-us"
title = "Victor Mateevitsi"
theme = "default"
relativeURLs = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
