baseURL = "/"
languageCode = "en-us"
title = "Victor Mateevitsi, PhD"
theme = "default"
relativeURLs = true
enableRobotsTXT = true

[imaging]
# See https://github.com/disintegration/imaging
# CatmullRom is a sharp bicubic filter which should fit the docs site well with its many screenshots.
# Note that you can also set this per image processing.
resampleFilter = "CatmullRom"

# Default JPEG quality setting. Default is 75.
quality = 75

anchor = "smart"

[params]
  js = ['js/external/jquery.js', 'js/external/bootstrap.js', 'js/external/rrssb.js', 'js/external/fontawesome.js', 'js/app.js' ]
  css = [ 'css/external/bootstrap.css', 'css/external/rrssb.css' ]



[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier= "posts"
    name = "posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "press"
    name = "press"
    url = "/press/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact/"
    weight = 5
