[build]
  publish = "public"
  command = "yarn build"
  functions = "functions/"

[build.environment]
  HUGO_VERSION = "0.78.2"
  NODE_VERSION = "15.2.1"
  NPM_VERSION = "15.2.1"
  YARN_VERSION = "1.22.10"

[context.deploy-preview]
  command = "yarn build:preview"

[context.deploy-preview.environment]
  HUGO_ENV = "staging"

[context.branch-deploy]
  command = "yarn build"
