[build]
  publish = "public"
  command = "yarn build"
  functions = "functions/"

[build.environment]
  HUGO_VERSION = "0.74.3"
  NODE_VERSION = "14.9.0"
  NPM_VERSION = "6.14.7"
  YARN_VERSION = "1.22.5"

[context.deploy-preview]
  command = "yarn build:preview"

[context.deploy-preview.environment]
  HUGO_ENV = "staging"

[context.branch-deploy]
  command = "yarn build"
