[build]
  publish = "public"
  command = "yarn build"
  functions = "functions/"

[build.environment]
  HUGO_VERSION = "0.88.0"
  NODE_VERSION = "16.10.0"
  NPM_VERSION = "7.24.0"
  YARN_VERSION = "1.22.15"

[context.deploy-preview]
  command = "yarn build:preview"

[context.deploy-preview.environment]
  HUGO_ENV = "staging"

[context.branch-deploy]
  command = "yarn build"
