# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  hugo: circleci/hugo@0.5.2
  yarn: itinerisltd/yarn@1.0.1
jobs:
  - hugo/build:
    html-proofer: true
    version: '0.69.2'

